### ISSUE TITLE
Integrating pubmed APIs

### ISSUE THREAD

**Issue by bmschmidt** [bmschmidt/pubmed-explorer#62]
So we have pubmed ids in the browser here--that means that any service that *returns* pubmed ids should be able to create a selection on the screen. That might be an entirely different way to implement https://github.com/bmschmidt/pubmed-explorer/issues/60 from @dkobak ; you could type "Lior Pachter" in, get a list of all his pubmed ids from some server in Bethesda, and then apply them to the chart. Would work for complicated things like subject headings, too!

**Comment by dkobak** [comment]
This is a great idea. It turns out, one can do this:

https://pubmed.ncbi.nlm.nih.gov/?term=dmitry+kobak%5BAuthor%5D&format=pmid&size=200

and get the list of PMIDs back!

Or this:

https://pubmed.ncbi.nlm.nih.gov/?term=lior+pachter%5BAuthor%5D&format=pmid&size=200

It seems to be limited by 200 hits though (one cannot set a higher number).

**Comment by bmschmidt** [comment]
Oh great. Is there documentation on this?

**Comment by dkobak** [comment]
No idea! But if you go here https://pubmed.ncbi.nlm.nih.gov/?term=lior+pachter&size=200 and click on "Display options", you can get it to display the list of PMIDs.

**Comment by dkobak** [comment]
So it works with any search query to PubMed (and they can get quite elaborate: one can search among authors/abstracts/etc).

**Comment by bmschmidt** [comment]
I'm wondering how/whether it differs from the entrez tools they offer:

[https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pmc&term=Lior%20Pachter%5Bauthor%5D&format=json&retmax=1000]

**Comment by bmschmidt** [comment]
Ah, you can just get more than 200 be setting a `page` parameter. https://pubmed.ncbi.nlm.nih.gov/?term=lior+pachter&format=pmid&size=20&page=2

**Comment by bmschmidt** [comment]
preliminary version (including full-text search for both authors and MeSH terms) is now up towards the end of the scrolly.
